In [1]:
import pandas as pd

In [3]:
https://www.football-data.co.uk/data.php

In [5]:
df_premier = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [6]:
df_premier

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

In [7]:
df_premier.rename(columns = {'Date' : 'date' , 'HomeTeam':'home_team'})

,Div,date,Time,home_team,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

In [ ]:
#Read multiple URLs using pandas

In [8]:
root = "https://www.football-data.co.uk/mmz4281/"

https://www.football-data.co.uk/mmz4281/2526/E0.csv
https://www.football-data.co.uk/mmz4281/2526/E1.csv
https://www.football-data.co.uk/mmz4281/2526/E2.csv
https://www.football-data.co.uk/mmz4281/2526/E3.csv
https://www.football-data.co.uk/mmz4281/2526/EC.csv

In [13]:
# creating list of leagues
leagues = ['E0','E2', 'E3']
frames  = []

#run a smiple for loop with leagues names and save the dataframe created in frames
for league in leagues:
    df = pd.read_csv(root + "2526" + "/" + league + ".csv")
    frames.append(df)

In [14]:
frames[1].head(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E2,01/08/2025,20:00,Luton,AFC Wimbledon,1,0,H,0,0,...,1.93,1.93,1.93,1.95,1.98,1.93,1.91,1.82,1.94,2.01
1,E2,02/08/2025,12:30,Cardiff,Peterboro,2,1,H,0,1,...,1.85,2.00,1.87,2.03,1.90,2.00,1.85,1.88,1.93,2.04
2,E2,02/08/2025,15:00,Blackpool,Stevenage,2,3,A,1,2,...,1.93,1.93,1.94,1.94,1.94,1.93,1.84,1.87,1.94,2.04

In [15]:
len(frames)

3

#now for multiple seasons .
https://www.football-data.co.uk/mmz4281/2425/E0.csv
https://www.football-data.co.uk/mmz4281/2324/E0.csv

In [22]:
#simply use a double forloop in this case to loop through and change season links as well
# creating list of leagues
leagues = ['E0','E2', 'E3']
frames  = []

#run a smiple for loop with leagues names and save the dataframe created in frames
for league in leagues:
    for season in range(15 , 25):
        df = pd.read_csv(root + str(season) + str(season + 1) + "/" + league + ".csv")
        df.insert(1 ,'season',season)
        frames.append(df)

In [23]:
len(frames)

30

In [25]:
frames[13]

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E2,18,04/08/2018,Accrington,Gillingham,0,2,A,0,2,...,1.77,19,-0.25,2.02,1.96,1.90,1.86,2.38,3.36,3.17
1,E2,18,04/08/2018,Barnsley,Oxford,4,0,H,2,0,...,1.92,18,-0.50,2.02,1.95,1.95,1.87,1.83,3.82,4.44
2,E2,18,04/08/2018,Burton,Rochdale,1,2,A,0,2,...,1.72,18,-0.50,2.21,2.13,1.76,1.72,2.88,3.28,2.62
3,E2,18,04/08/2018,Coventry,Scunthorpe,1,2,A,0,0,...,1.67,20,-0.25,2.05,1.97,1.91,1.84,2.59,3.23,2.96
4,E2,18,04/08/2018,Fleetwood Town,AFC Wimbledon,0,1,A,0,0,...,1.65,18,-0.25,1.93,1.86,2.00,1.94,2.02,3.43,4.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,18,04/05/2019,Plymouth,Scunthorpe,3,2,H,2,1,...,2.02,18,-0.25,1.95,1.87,2.02,1.96,1.88,4.08,3.92
548,E2,18,04/05/2019,Portsmouth,Accrington,1,1,D,0,0,...,2.15,18,-1.25,1.98,1.93,2.00,1.89,1.44,4.61,7.60
549,E2,18,04/05/2019,Shrewsbury,Walsall,0,0,D,0,0,...,1.75,17,0.00,2.01,1.95,1.94,1.88,2.38,3.76,2.89
550,E2,18,04/05/2019,Southend,Sunderland,2,1,H,1,0,...,1.84,16,0.00,2.06,2.01,1.87,1.82,2.97,3.71,2.35
551,E2,18,04/05/2019,Wycombe,Fleetwood Town,1,0,H,0,0,...,1.71,18,-0.50,2.20,2.11,1.79,1.73,2.39,3.34,3.20

In [21]:
#Simply orgranise all Data in Dictionary

In [26]:
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [27]:
dict_countries['German Bundesliga']

'D1'

In [33]:
frames  = []
dict_historical_data = {}
#run a smiple for loop with leagues names and save the dataframe created in frames
for league in dict_countries:
    for season in range(15 , 25):
        df = pd.read_csv(root + str(season) + str(season + 1) + "/" + dict_countries[league] + ".csv")
        df.insert(1 ,'season',season)
        frames.append(df) 
    df_frames = pd.concat(frames)
    dict_historical_data[league] = df_frames # assigning dataframe to a new dictionary

In [34]:
dict_historical_data['Spanish La Liga']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,1XBCH,1XBCD,1XBCA,BFECH,BFECD,BFECA,BFEC>2.5,BFEC<2.5,BFECAHH,BFECAHA
0,SP1,15,21/08/15,Malaga,Sevilla,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,15,22/08/15,Ath Madrid,Las Palmas,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,15,22/08/15,Espanol,Getafe,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,15,22/08/15,La Coruna,Sociedad,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,15,22/08/15,Vallecano,Valencia,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,24,24/05/2025,Getafe,Celta,1,2,A,1,1,...,4.85,3.88,1.77,5.30,3.9,1.79,2.08,1.89,1.95,2.03
376,SP1,24,24/05/2025,Vallecano,Mallorca,0,0,D,0,0,...,1.53,4.19,7.29,1.50,4.6,8.20,2.10,1.87,1.85,2.14
377,SP1,24,25/05/2025,Girona,Ath Madrid,0,4,A,0,0,...,3.48,3.57,2.16,3.50,3.7,2.24,1.60,2.64,2.04,1.94
378,SP1,24,25/05/2025,Villarreal,Sevilla,4,2,H,3,1,...,1.75,4.42,4.30,1.80,4.3,4.60,1.60,2.62,2.03,1.95
379,SP1,24,25/05/2025,Ath Bilbao,Barcelona,0,3,A,0,2,...,3.49,4.00,2.03,3.35,4.0,2.18,1.47,3.05,2.07,1.91