In [2]:
import pandas as pd
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
df["math score"]

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [6]:
type(["math score"])

list

In [15]:
mini = df["math score"].min()
meani = df["math score"].mean()
maxi = df["math score"].max()
print(mini)
print(meani)
print(maxi)

0
66.089
100

In [16]:
df["gender"]

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [18]:
df["gender"].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [22]:
random = df[["gender" , "math score" , "reading score"]]
random.head()

   gender  math score  reading score
0  female          72             72
1  female          69             90
2  female          90             95
3    male          47             57
4    male          76             78

In [28]:
random.shape

(1000, 3)

In [27]:
random.describe()

       math score  reading score
count  1000.00000    1000.000000
mean     66.08900      69.169000
std      15.16308      14.600192
min       0.00000      17.000000
25%      57.00000      59.000000
50%      66.00000      70.000000
75%      77.00000      79.000000
max     100.00000     100.000000

In [38]:
summary_dict = {
    "Gender": df["gender"],
    "Lunch": df["lunch"],
    "Test preparation course": df["test preparation course"],
    "MathScore": df["math score"]
}

df_student_summary = pd.DataFrame(summary_dict)

In [39]:
df_student_summary.head(10)

   Gender         Lunch Test preparation course  MathScore
0  female      standard                    none         72
1  female      standard               completed         69
2  female      standard                    none         90
3    male  free/reduced                    none         47
4    male      standard                    none         76
5  female      standard                    none         71
6  female      standard               completed         88
7    male  free/reduced                    none         40
8    male  free/reduced               completed         64
9  female  free/reduced                    none         38

In [44]:
score = df_student_summary[["Gender" , "MathScore"]]
score

     Gender  MathScore
0    female         72
1    female         69
2    female         90
3      male         47
4      male         76
..      ...        ...
995  female         88
996    male         62
997  female         59
998  female         68
999  female         77

[1000 rows x 2 columns]

In [60]:
df["total_score"] = df["math score"] + df["reading score"] + df["writing score"]
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [59]:
df["average_score"] = df["total_score"] /3 
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [61]:
df[["math score", "reading score", "writing score", "total_score", "average_score"]].head()

   math score  reading score  writing score  total_score  average_score
0          72             72             74          218      72.666667
1          69             90             88          247      82.333333
2          90             95             93          278      92.666667
3          47             57             44          148      49.333333
4          76             78             75          229      76.333333

In [62]:
df["passed_math"] = df["math score"] >= 50

In [64]:
df["passed_math"].value_counts()

passed_math
True     865
False    135
Name: count, dtype: int64

In [73]:
means = pd.Series({
    "Math": df["math score"].mean(),
    "Reading": df["reading score"].mean(),
    "Writing": df["writing score"].mean()
})

print("Math Average:", means["Math"])
print("Reading Average:", means["Reading"])
print("Writing Average:", means["Writing"])

best_subject = means.idxmax()
best_avg = means.max()

print("Best Subject:", best_subject, f"({best_avg})")

Math Average: 66.089
Reading Average: 69.169
Writing Average: 68.054
Best Subject: Reading (69.169)

In [75]:
df["strong_student"] = df["average_score"] >= 80
df["strong_student"].value_counts()

strong_student
False    802
True     198
Name: count, dtype: int64