In [5]:
import pandas as pd

df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
import numpy as np

In [9]:
#create random numbers for coloums for testing
series1 = np.random.randint(1 , 100 , size=1000)

In [11]:
df = df.assign(score1 = series1)

In [12]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1
0,female,group B,bachelor's degree,standard,none,72,72,74,11
1,female,group C,some college,standard,completed,69,90,88,81
2,female,group B,master's degree,standard,none,90,95,93,9
3,male,group A,associate's degree,free/reduced,none,47,57,44,56
4,male,group C,some college,standard,none,76,78,75,18
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,49
996,male,group C,high school,free/reduced,none,62,55,55,85
997,female,group C,high school,free/reduced,completed,59,71,65,50
998,female,group D,some college,standard,completed,68,78,77,61
999,female,group D,some college,free/reduced,none,77,86,86,18

In [13]:
df2 =  df.assign(totalscore = df["math score"]  + df["reading score"] + df["writing score"])

In [15]:
df2 = df2.assign(average_score = df2["totalscore"] / 3)

In [17]:
df2.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,totalscore,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,11,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,81,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,9,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,56,148,49.333333
4,male,group C,some college,standard,none,76,78,75,18,229,76.333333

In [18]:
df2.insert(0 ,'test_frame', series1)

In [19]:
df2

,test_frame,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,totalscore,average_score
0,11,female,group B,bachelor's degree,standard,none,72,72,74,11,218,72.666667
1,81,female,group C,some college,standard,completed,69,90,88,81,247,82.333333
2,9,female,group B,master's degree,standard,none,90,95,93,9,278,92.666667
3,56,male,group A,associate's degree,free/reduced,none,47,57,44,56,148,49.333333
4,18,male,group C,some college,standard,none,76,78,75,18,229,76.333333
...,...,...,...,...,...,...,...,...,...,...,...,...
995,49,female,group E,master's degree,standard,completed,88,99,95,49,282,94.000000
996,85,male,group C,high school,free/reduced,none,62,55,55,85,172,57.333333
997,50,female,group C,high school,free/reduced,completed,59,71,65,50,195,65.000000
998,61,female,group D,some college,standard,completed,68,78,77,61,223,74.333333
999,18,female,group D,some college,free/reduced,none,77,86,86,18,249,83.000000

In [20]:
df2['math score'].sum()

np.int64(66089)

In [21]:
df2['math score'].count()

np.int64(1000)

In [22]:
df2['math score'].mean()

np.float64(66.089)

In [23]:
df2['math score'].max()

100

In [24]:
df2['math score'].min()

0

In [25]:
df2["average_score_rounded"] = df2["average_score"].round(2)

In [26]:
df2[["average_score" , "average_score_rounded"]].head()

   average_score  average_score_rounded
0      72.666667                  72.67
1      82.333333                  82.33
2      92.666667                  92.67
3      49.333333                  49.33
4      76.333333                  76.33

In [28]:
df2["passed_nuts"] = ((df2["math score"] >= 50 ) & (df2["reading score"] >= 50) &
    (df2["writing score"] >= 50))

In [29]:
df2["passed_nuts"].value_counts()

passed_nuts
True     812
False    188
Name: count, dtype: int64

In [30]:
df2["gender"].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [31]:
df2["lunch"].value_counts()

lunch
standard        645
free/reduced    355
Name: count, dtype: int64

In [32]:
df2["race/ethnicity"].value_counts()

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

In [34]:
df2["gender"].value_counts(normalize = True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [36]:
#find the percentage after normalizing the hoe 
df2["gender"].value_counts(normalize = True)  * 100

gender
female    51.8
male      48.2
Name: proportion, dtype: float64

In [37]:
#chapter nine -=--- Nein nein NEIN sort ing stuff I guess
df2.sort_values("math score").head()

,test_frame,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,totalscore,average_score,average_score_rounded,passed_nuts
59,74,female,group C,some high school,free/reduced,none,0,17,10,74,27,9.000000,9.00,False
980,46,female,group B,high school,free/reduced,none,8,24,23,46,55,18.333333,18.33,False
17,9,female,group B,some high school,free/reduced,none,18,32,28,9,78,26.000000,26.00,False
787,67,female,group B,some college,standard,none,19,38,32,67,89,29.666667,29.67,False
145,94,female,group C,some college,free/reduced,none,22,39,33,94,94,31.333333,31.33,False

In [39]:
df2.sort_values("math score" , ascending = False).head(100)

,test_frame,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,totalscore,average_score,average_score_rounded,passed_nuts
962,41,female,group E,associate's degree,standard,none,100,100,100,41,300,100.000000,100.00,True
625,59,male,group D,some college,standard,completed,100,97,99,59,296,98.666667,98.67,True
458,62,female,group E,bachelor's degree,standard,none,100,100,100,62,300,100.000000,100.00,True
623,91,male,group A,some college,standard,completed,100,96,86,91,282,94.000000,94.00,True
451,94,female,group E,some college,standard,none,100,92,97,94,289,96.333333,96.33,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,18,female,group C,bachelor's degree,standard,none,86,92,87,18,265,88.333333,88.33,True
447,49,male,group C,high school,standard,completed,86,81,80,49,247,82.333333,82.33,True
291,80,male,group D,some high school,standard,none,86,73,70,80,229,76.333333,76.33,True
990,89,male,group E,high school,free/reduced,completed,86,81,75,89,242,80.666667,80.67,True
223,90,male,group D,some high school,standard,none,86,80,75,90,241,80.333333,80.33,True

In [40]:
df2.sort_values("average_score", ascending=False).head(10)

,test_frame,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,totalscore,average_score,average_score_rounded,passed_nuts
916,88,male,group E,bachelor's degree,standard,completed,100,100,100,88,300,100.000000,100.00,True
458,62,female,group E,bachelor's degree,standard,none,100,100,100,62,300,100.000000,100.00,True
962,41,female,group E,associate's degree,standard,none,100,100,100,41,300,100.000000,100.00,True
114,29,female,group E,bachelor's degree,standard,completed,99,100,100,29,299,99.666667,99.67,True
179,93,female,group D,some high school,standard,completed,97,100,100,93,297,99.000000,99.00,True
712,94,female,group D,some college,standard,none,98,100,99,94,297,99.000000,99.00,True
165,89,female,group C,bachelor's degree,standard,completed,96,100,100,89,296,98.666667,98.67,True
625,59,male,group D,some college,standard,completed,100,97,99,59,296,98.666667,98.67,True
903,96,female,group D,bachelor's degree,free/reduced,completed,93,100,100,96,293,97.666667,97.67,True
149,21,male,group E,associate's degree,free/reduced,completed,100,100,93,21,293,97.666667,97.67,True

In [44]:
df2.sort_values("average_score", ascending=False)[["gender",
    "average_score"
]].head(10)

     gender  average_score
916    male     100.000000
458  female     100.000000
962  female     100.000000
114  female      99.666667
179  female      99.000000
712  female      99.000000
165  female      98.666667
625    male      98.666667
903  female      97.666667
149    male      97.666667

In [45]:
df2.sort_values(["gender" , "average_score"] , ascending = [True , False]).head(10)

,test_frame,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,totalscore,average_score,average_score_rounded,passed_nuts
458,62,female,group E,bachelor's degree,standard,none,100,100,100,62,300,100.000000,100.00,True
962,41,female,group E,associate's degree,standard,none,100,100,100,41,300,100.000000,100.00,True
114,29,female,group E,bachelor's degree,standard,completed,99,100,100,29,299,99.666667,99.67,True
179,93,female,group D,some high school,standard,completed,97,100,100,93,297,99.000000,99.00,True
712,94,female,group D,some college,standard,none,98,100,99,94,297,99.000000,99.00,True
165,89,female,group C,bachelor's degree,standard,completed,96,100,100,89,296,98.666667,98.67,True
685,63,female,group E,master's degree,standard,completed,94,99,100,63,293,97.666667,97.67,True
903,96,female,group D,bachelor's degree,free/reduced,completed,93,100,100,96,293,97.666667,97.67,True
566,40,female,group E,bachelor's degree,free/reduced,completed,92,100,100,40,292,97.333333,97.33,True
957,74,female,group D,master's degree,standard,none,92,100,100,74,292,97.333333,97.33,True

In [50]:
df2.sort_values(['race/ethnicity'] , ascending = True , key = lambda a:a.str.lower())

,test_frame,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,totalscore,average_score,average_score_rounded,passed_nuts
778,86,female,group A,some college,standard,completed,72,79,82,86,233,77.666667,77.67,True
546,77,female,group A,some high school,standard,completed,92,100,97,77,289,96.333333,96.33,True
820,83,female,group A,some high school,standard,completed,85,90,92,83,267,89.000000,89.00,True
741,85,female,group A,associate's degree,free/reduced,none,37,57,56,85,150,50.000000,50.00,False
305,67,male,group A,some college,standard,none,69,67,69,67,205,68.333333,68.33,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,65,male,group E,associate's degree,standard,completed,71,74,68,65,213,71.000000,71.00,True
293,21,female,group E,bachelor's degree,standard,none,65,73,75,21,213,71.000000,71.00,True
289,43,male,group E,some high school,standard,completed,77,76,77,43,230,76.666667,76.67,True
206,53,male,group E,bachelor's degree,standard,none,82,62,62,53,206,68.666667,68.67,True
499,83,male,group E,some college,standard,none,76,71,72,83,219,73.000000,73.00,True

In [51]:
#number 10 set_index() and sort_index()

In [56]:
import random
import numpy as np

In [60]:
#create non repeating values for the index
new_index = np.arange(0 , 1000)
new_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [62]:
random.shuffle(new_index)
new_index

array([626, 912, 113, 920, 110, 371,  84, 718, 494,  29, 721, 822, 189,
       514, 201, 236, 249, 881, 750, 380,  37, 594, 623, 318, 777, 260,
       769, 723, 923, 392, 685, 140, 157, 814, 339, 964, 310, 182, 519,
       282, 209, 286,  87,  71, 852, 727, 451, 388, 196, 680, 416, 234,
        41, 440, 311, 580, 221, 239, 172, 703, 638, 665, 398, 874, 411,
        85, 431, 424, 858, 457, 579, 871, 216, 183, 953, 689, 851, 336,
       412, 271, 315, 143, 872, 303, 778, 442, 913, 181, 342, 861, 870,
       752, 783, 937, 819, 565, 830, 619, 959, 890, 570, 133, 586, 656,
       971, 152, 496,  12, 106, 894, 969, 637, 101, 955, 910, 576, 788,
       120, 223, 667, 900, 593, 111, 448, 916, 426, 744, 253, 993, 668,
       954,  47, 491, 466, 204, 347, 459, 305, 549, 571, 225, 876, 740,
       947, 827, 445, 264, 695,  75,  99, 663, 899, 653, 229, 261, 928,
       941, 505, 419, 135, 279, 220, 853, 481, 483, 985, 564, 256, 529,
       652, 248, 323, 307, 628, 259,  46, 547, 673,  10, 836, 128, 269,
       808, 624, 821, 883, 676, 458, 961, 192, 507, 476, 800, 214, 609,
       866, 455, 155, 764, 188, 805, 997, 757, 195,   5, 400,  53, 406,
       484, 811, 472, 367, 704, 266, 511, 860,  69, 643, 394, 962, 725,
       129, 745, 796,  72, 317, 301,   2, 293, 473, 563, 414, 835, 200,
       144, 399, 168, 154,  80, 845, 488, 517, 702, 554, 875, 782, 361,
       646, 862, 391, 463, 265,  36, 733, 772, 224, 785, 596, 542, 683,
        13, 797, 697, 267, 566,  82,  97, 332, 664, 222, 832, 495, 287,
       528, 240, 290, 452,  64, 895, 130, 877, 574, 645, 603, 688, 632,
       551, 810, 661, 207,  65, 965, 911, 402, 467, 589, 362, 774, 973,
       942, 648, 104, 823, 167, 708, 940, 850,   1, 478, 598,  23,  96,
       219, 163, 824, 436, 758, 343, 548, 270, 108, 241, 103,  62, 612,
       334, 410, 117, 124, 606, 408,  38, 405, 349, 540, 828, 105, 641,
       283, 107, 611, 591, 773, 199, 610,  74, 116,  89, 857, 932, 389,
       696, 418, 615, 818, 561, 970, 294, 715, 536, 503, 856, 742, 109,
       794, 679, 498, 604, 387,  95, 539, 989, 377, 501, 976, 262, 806,
       575,  55, 724, 831, 918, 952, 847, 934, 734,   9, 340, 430, 644,
       546, 203, 171, 975, 194, 722, 131, 754,  43,  77, 250, 118, 659,
       277, 500, 202, 762, 291,  70, 977, 480, 555,  94, 755,  54, 401,
       654,  59, 162, 684, 837, 924, 707, 359, 607, 710, 990, 421, 123,
       776, 393, 348, 622, 736, 846, 693, 994, 608, 313, 933, 712, 735,
       276, 456, 506, 986, 568, 206, 726, 475, 137, 126, 520, 709, 922,
       552, 873, 142, 233, 355, 158, 482, 378, 132, 145, 344,  52, 616,
       280,  86,  78, 485, 272, 338, 930, 732, 487, 468, 425, 268, 197,
        92, 210, 886, 802,  93, 801, 289, 825, 599, 687, 382, 490, 884,
       651, 951, 174, 345, 263, 700, 882, 390, 906, 147, 324, 437,  68,
       226,  19, 936,   0,  24, 302, 427,  15, 386, 738,  44, 211, 244,
       949, 235,  91, 465,  57, 743, 902, 474, 938, 567,  31,  25, 768,
       885, 322, 816, 903, 328, 815, 184, 896, 497, 530,   7, 176, 316,
       982, 493,  22, 187, 292, 251, 867, 254,  73, 284, 122, 146, 771,
       692, 631, 320, 892, 312, 972, 642, 374, 887, 597, 833, 713, 469,
       298, 569, 789, 577, 533, 588,  33,  27, 550, 807, 691, 931, 817,
       333, 545, 919, 477, 446, 633,  21, 422,  51, 335, 175, 460, 799,
       694, 288, 243, 255, 979, 513, 138, 403,  14, 834, 865, 756, 356,
       161, 531, 309, 698, 252, 809, 590, 381, 751, 935, 165, 231, 706,
       843, 948, 761,  35, 553, 791, 258, 169, 534, 212, 720, 763, 139,
       516, 543,   3, 629, 461, 996, 987, 746, 285, 417, 897, 613, 560,
       429, 119, 677,  58, 228,  42, 749, 238, 489, 329, 141, 889, 660,
        11,  48, 657, 274, 662, 716, 787, 674, 844, 618, 159, 701, 177,
       820,  39, 999, 510, 433, 640, 242, 729, 699, 462, 396, 397, 614,
       148, 842, 893, 370, 759,  32, 153, 173, 205, 927, 840, 518, 730,
       741, 956, 686, 943, 647, 562, 601, 635, 151,  49, 907, 351, 502,
       479, 166, 521, 136,  61,  28, 100, 447, 295, 357, 186, 967, 578,
       537, 650, 432, 960,  17, 218, 372, 185, 304, 854, 281, 572, 980,
       296, 669, 868, 978, 375, 690, 826, 515, 383, 983, 556,  40,  81,
       353, 213, 929, 330, 950, 524, 395, 926, 246, 587, 331, 341, 149,
       888, 944, 670, 974, 559, 198,  50, 164, 864, 232, 984, 434, 275,
       508, 602, 634, 957, 966,  26, 790, 450, 114, 804, 193, 354, 102,
       711, 786, 584, 779, 523, 731, 901, 848, 681, 127, 581, 908, 156,
       813, 839, 671, 784, 981, 350, 829, 369, 125, 535, 525, 988, 672,
       765, 583, 306, 364,  88, 247, 327, 415, 444,  30, 504, 278,  34,
       855, 770,   6, 208, 879,  60,  16, 385, 215, 760, 321, 636, 453,
       781, 891, 150, 325,  83, 115, 544, 352, 958, 121, 179, 717, 363,
       413, 237, 915, 945, 869, 509, 592,  18, 904, 365, 346, 666, 963,
       798, 191, 486, 878, 714, 849, 435, 557, 170, 573, 297, 939,  20,
       190, 492, 838, 522, 512,  98, 917, 728, 600, 991, 621, 439, 376,
       898, 678, 905, 541, 605, 753, 639, 675, 775, 379, 319, 767, 112,
       368, 909, 471, 160, 705, 337, 443, 299, 649, 300,  90, 859, 227,
       407, 658, 803, 454, 404, 585, 998, 449, 358, 655, 795, 739, 438,
       180, 326, 420, 780,  56,  66, 719, 373, 766, 134, 499, 464, 627,
       178, 792, 441,  76, 423, 863,   8, 409, 230, 620, 366,   4, 273,
       532, 308, 841, 748, 582, 682, 314, 245, 217, 470, 968,  45, 812,
       595, 946, 625, 428, 793, 992,  79, 925, 527, 526,  67, 257, 630,
       384, 538, 995, 921,  63, 360, 880, 558, 737, 617, 914, 747])

In [66]:
##Set index 
df_indexed = df2.set_index("gender")

In [67]:
df_indexed

,test_frame,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,totalscore,average_score,average_score_rounded,passed_nuts
gender,,,,,,,,,,,,,
female,11,group B,bachelor's degree,standard,none,72,72,74,11,218,72.666667,72.67,True
female,81,group C,some college,standard,completed,69,90,88,81,247,82.333333,82.33,True
female,9,group B,master's degree,standard,none,90,95,93,9,278,92.666667,92.67,True
male,56,group A,associate's degree,free/reduced,none,47,57,44,56,148,49.333333,49.33,False
male,18,group C,some college,standard,none,76,78,75,18,229,76.333333,76.33,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
female,49,group E,master's degree,standard,completed,88,99,95,49,282,94.000000,94.00,True
male,85,group C,high school,free/reduced,none,62,55,55,85,172,57.333333,57.33,True
female,50,group C,high school,free/reduced,completed,59,71,65,50,195,65.000000,65.00,True
female,61,group D,some college,standard,completed,68,78,77,61,223,74.333333,74.33,True
female,18,group D,some college,free/reduced,none,77,86,86,18,249,83.000000,83.00,True

In [68]:
df2.sort_index()

,test_frame,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,totalscore,average_score,average_score_rounded,passed_nuts
0,11,female,group B,bachelor's degree,standard,none,72,72,74,11,218,72.666667,72.67,True
1,81,female,group C,some college,standard,completed,69,90,88,81,247,82.333333,82.33,True
2,9,female,group B,master's degree,standard,none,90,95,93,9,278,92.666667,92.67,True
3,56,male,group A,associate's degree,free/reduced,none,47,57,44,56,148,49.333333,49.33,False
4,18,male,group C,some college,standard,none,76,78,75,18,229,76.333333,76.33,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,49,female,group E,master's degree,standard,completed,88,99,95,49,282,94.000000,94.00,True
996,85,male,group C,high school,free/reduced,none,62,55,55,85,172,57.333333,57.33,True
997,50,female,group C,high school,free/reduced,completed,59,71,65,50,195,65.000000,65.00,True
998,61,female,group D,some college,standard,completed,68,78,77,61,223,74.333333,74.33,True
999,18,female,group D,some college,free/reduced,none,77,86,86,18,249,83.000000,83.00,True

In [71]:
df_renamed = df.rename(columns = {
"math score" : "math_score" , 
"reading score" : "reading_score"
})

In [73]:
df_renamed

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math_score,reading_score,writing score,score1
0,female,group B,bachelor's degree,standard,none,72,72,74,11
1,female,group C,some college,standard,completed,69,90,88,81
2,female,group B,master's degree,standard,none,90,95,93,9
3,male,group A,associate's degree,free/reduced,none,47,57,44,56
4,male,group C,some college,standard,none,76,78,75,18
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,49
996,male,group C,high school,free/reduced,none,62,55,55,85
997,female,group C,high school,free/reduced,completed,59,71,65,50
998,female,group D,some college,standard,completed,68,78,77,61
999,female,group D,some college,free/reduced,none,77,86,86,18

In [76]:
df_renamed.rename(index ={0 : 'A' , 1 : 'B' , 2 : 'C'} , inplace = True)

In [77]:
df_renamed

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math_score,reading_score,writing score,score1
A,female,group B,bachelor's degree,standard,none,72,72,74,11
B,female,group C,some college,standard,completed,69,90,88,81
C,female,group B,master's degree,standard,none,90,95,93,9
3,male,group A,associate's degree,free/reduced,none,47,57,44,56
4,male,group C,some college,standard,none,76,78,75,18
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,49
996,male,group C,high school,free/reduced,none,62,55,55,85
997,female,group C,high school,free/reduced,completed,59,71,65,50
998,female,group D,some college,standard,completed,68,78,77,61
999,female,group D,some college,free/reduced,none,77,86,86,18